[package]
name = "lazymc-docker-proxy"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.0"

[dependencies]
bollard = "0.17.1"
clap = { version = "4.5.16", features = ["derive"] }
ctrlc = { version = "3.4.5", features = ["termination"] }
futures = "0.3.30"
log = "0.4"
pretty_env_logger = "0.5"
regex = "1.10.6"
serde = "1.0.208"
tokio = { version = "1.39.0", default-features = false, features = [
    "rt-multi-thread",
] }
toml = "0.8.19"
version-compare = "0.2.0"
