[package]
name = "lazymc-docker-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", default-features = false, features = ["full"] }
toml = "0.8.15"
bollard = "0.16.1"
clap = { version = "4.5.10", features = ["derive"] }
serde = "1.0.204"
log = "0.4.22"
futures = "0.3.30"
