[package]
name = "lazymc-docker-proxy"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.0"

[dependencies]
bollard = "0.17.0"
clap = { version = "4.5.11", features = ["derive"] }
ctrlc = { version = "3.4.4", features = ["termination"] }
futures = "0.3.30"
log = "0.4"
pretty_env_logger = "0.5"
serde = "1.0.204"
tokio = { version = "1.39.0", default-features = false, features = [
    "rt-multi-thread",
] }
toml = "0.8.15"
