[package]
name = "lazymc-docker-proxy"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.0"

[dependencies]
bollard = "0.18.1"
clap = { version = "4.5.38", features = ["derive"] }
ctrlc = { version = "3.4.6", features = ["termination"] }
futures = "0.3.31"
log = "0.4"
pretty_env_logger = "0.5"
regex = "1.11.1"
serde = "1.0.219"
tokio = { version = "1.45.0", default-features = false, features = [
    "rt-multi-thread",
] }
toml = "0.8.22"
version-compare = "0.2.0"
