name: Integration Test
on:
  push:
    branches:
      - master
      - main
  pull_request:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  find-tests:
    name: Find Tests
    runs-on: ubuntu-latest

    outputs:
      folders: ${{ steps.jobs.outputs.folders }}
    steps:
      - uses: actions/checkout@v5

      - id: jobs
        uses: kmanimaran/list-folder-action@v4
        with:
          path: ./tests/bats

  test:
    needs: [find-tests]
    strategy:
      matrix:
        inputs: ${{fromJson(needs.find-tests.outputs.folders)}}

    name: Run Bats Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Run tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 5
          command: bats ./tests/bats/${{ matrix.inputs }}
      
